name: C/C++ CI


on:
  push:
    branches: [ "portable" ]
  pull_request:
    branches: [ "portable" ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - uses: actions/checkout@v4
    - name: configure
      run: premake5 gmake && apt install build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libasound2-dev
    - name: make
      run: cd build && make

